FROM mcr.microsoft.com/dotnet/core/sdk AS build
WORKDIR /app

COPY . Web
WORKDIR /app/Web
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet AS runtime
WORKDIR /app
COPY --from=build /app/Web/out .
ENTRYPOINT ["dotnet", "News.Web.dll"]
